---
- hosts: app
  become: yes
  collections:
    - community.docker

  vars:
    app_dir: /opt/myapp
    registry: "ghcr.io/hieu-do-seta"
    image_tag: "{{ image_tag }}"

  tasks:
    - name: Docker login to GHCR
      community.docker.docker_login:
        registry_url: ghcr.io
        username: "{{ lookup('env', 'GITHUB_ACTOR') }}"
        password: "{{ lookup('env', 'GITHUB_TOKEN') }}"

    - name: Pull backend image
      community.docker.docker_image:
        name: "{{ registry }}/backend"
        tag: "{{ image_tag }}"
        source: pull

    - name: Run backend container
      community.docker.docker_container:
        name: backend
        image: "{{ registry }}/backend:{{ image_tag }}"
        env_file: "{{ app_dir }}/.env"
        ports:
          - "3000:3000"
        recreate: yes
        restart_policy: unless-stopped

    # (Tuỳ chọn) Thêm frontend tương tự nếu cần
    # - name: Pull frontend image
    #   community.docker.docker_image:
    #     name: "{{ registry }}/frontend"
    #     tag: "{{ image_tag }}"
    #     source: pull

    # - name: Run frontend container
    #   community.docker.docker_container:
    #     name: frontend
    #     image: "{{ registry }}/frontend:{{ image_tag }}"
    #     env_file: "{{ app_dir }}/.env"
    #     ports:
    #       - "80:80"
    #     recreate: yes
    #     restart_policy: unless-stopped
