# infra-ansible/ansible/deploy.yml
---
- hosts: app
  become: yes
  collections:
    - community.docker

  vars:
    app_dir: /opt/myapp
    registry: "{{ registry }}"
    image_tag: "{{ image_tag }}"

  tasks:
    - name: Pull backend image for amd64
      community.docker.docker_image:
        name: "{{ registry }}/backend"
        tag: "{{ image_tag }}"
        source: pull
        platform: linux/amd64

    - name: Run backend container for amd64
      community.docker.docker_container:
        name: backend
        image: "{{ registry }}/backend:{{ image_tag }}"
        env_file: "{{ app_dir }}/.env"
        ports:
          - "3000:3000"
        recreate: yes
        restart_policy: unless-stopped
        platform: linux/amd64

    # - name: Pull frontend image for amd64
    #   community.docker.docker_image:
    #     name: "{{ registry }}/frontend"
    #     tag: "{{ image_tag }}"
    #     source: pull
    #     platform: linux/amd64

    # - name: Run frontend container for amd64
    #   community.docker.docker_container:
    #     name: frontend
    #     image: "{{ registry }}/frontend:{{ image_tag }}"
    #     env_file: "{{ app_dir }}/.env"
    #     ports:
    #       - "80:80"
    #     recreate: yes
    #     restart_policy: unless-stopped
    #     platform: linux/amd64
