---
- hosts: app
  become: yes
  collections:
    - community.docker

  vars:
    app_dir: /opt/myapp
    registry: "ghcr.io/{{ github_actor }}"
    image_tag: "{{ image_tag }}"

  tasks:
    - name: Docker login to GHCR (nếu image private, có thể xoá nếu public)
      ansible.builtin.shell: |
        echo "{{ github_token }}" | docker login ghcr.io -u {{ github_actor }} --password-stdin

    - name: Pull backend image
      community.docker.docker_image:
        name: "{{ registry }}/backend"
        tag: "{{ image_tag }}"
        source: pull

    - name: Run backend container
      community.docker.docker_container:
        name: backend
        image: "{{ registry }}/backend:{{ image_tag }}"
        env_file: "{{ app_dir }}/.env"
        ports:
          - "3000:3000"
        recreate: yes
        restart_policy: unless-stopped
