- hosts: app
  become: yes
  vars:
    app_dir: /opt/myapp

  tasks:
    - name: Pull backend image
      docker_image:
        name: "{{ registry }}/backend"
        tag: "{{ image_tag }}"
        source: pull

    - name: Run backend container
      docker_container:
        name: backend
        image: "{{ registry }}/backend:{{ image_tag }}"
        state: started
        restart_policy: unless-stopped
        env_file: "{{ app_dir }}/.env"
        ports:
          - "3000:3000"

    