name: App CI/CD (Dev)

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: "dev"

permissions:
  contents: read
  packages: write

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" \
            | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & Push Backend (arm64)
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -f code/backend/Dockerfile \
            -t ghcr.io/${{ github.repository_owner }}/backend:${{ github.sha }} \
            code/backend \
            --push

      - name: Build & Push Frontend
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ghcr.io/${{ github.repository_owner }}/frontend:${{ github.sha }} \
            -f code/frontend/Dockerfile \
            code/frontend \
            --push

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout infra-ansible
        uses: actions/checkout@v3
        with:
          path: infra-ansible

      - name: Setup SSH key (Dev)
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEV_KEY }}" > ~/.ssh/dev-key.pem
          chmod 600 ~/.ssh/dev-key.pem

      - name: Tạo SSH config với ProxyJump (Dev)
        run: |
          cat >> ~/.ssh/config <<EOF
          Host dev-bastion
            HostName ${{ secrets.DEV_BASTION_IP }}
            User ubuntu
            IdentityFile ~/.ssh/dev-key.pem
            StrictHostKeyChecking no

          Host dev-app
            HostName ${{ secrets.DEV_SERVER_IP }}
            User ubuntu
            IdentityFile ~/.ssh/dev-key.pem
            ProxyJump dev-bastion
            StrictHostKeyChecking no

          Host dev-frontend
            HostName ${{ secrets.DEV_FRONTEND_IP }}
            User ubuntu
            IdentityFile ~/.ssh/dev-key.pem
            StrictHostKeyChecking no
          EOF
          chmod 600 ~/.ssh/config

      - name: Sinh inventory.ini (Dev)
        run: |
          echo "[app]" > infra-ansible/envs/dev/inventory.ini
          echo "dev-app" >> infra-ansible/envs/dev/inventory.ini
          echo "" >> infra-ansible/envs/dev/inventory.ini
          echo "[frontend]" >> infra-ansible/envs/dev/inventory.ini
          echo "dev-frontend" >> infra-ansible/envs/dev/inventory.ini

      - name: Chạy Ansible deploy (Dev)
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook \
            -i infra-ansible/envs/dev/inventory.ini \
            --private-key ~/.ssh/dev-key.pem \
            -b \
            --extra-vars "registry=ghcr.io/${{ github.repository_owner }} image_tag=${{ needs.build_and_push.outputs.image_tag }} github_actor=${{ github.actor }} github_token=${{ secrets.GITHUB_TOKEN }}" \
            infra-ansible/ansible/deploy.yml
