name: Debug Assume Role

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: "dev"
        
jobs:
  debug-assume-role:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::802280247092:role/github-actions-ecr-role
          role-session-name: github-actions
          aws-region: ap-southeast-1

      - name: Print caller identity
        run: aws sts get-caller-identity
